language: python
python:
  # version of python.
  - 3.7
os:
  # os building
  - linux
install:
  # install packages.
  - pip install -r ./requirements.txt
before_script:
  - pip install pywifi
script:
  - python WifiBF.py -v

deploy:
  github-token: $GITHUB_TOKEN